### ISSUE TITLE
can't remove twitter elements on microsoft edge

### ISSUE THREAD

**Issue by ffelek** [LukeBriggsDev/calmer-internet#1]
youtube and instagram works perfectly but can't remove twitter elements.

browser specs = Version 94.0.992.50 (Official build) (64-bit)

**Comment by LukeBriggsDev** [comment]
Hi @flunitraz, could you please tell me which language your Twitter is set to

**Comment by LukeBriggsDev** [comment]
@flunitraz I have created a new release which should hopefully fix your issue. Please load the release as an unpacked extension and tell me if it works. I have also submitted the release to the Edge, Chrome, and Firefox add-on stores and they are under review

**Comment by LukeBriggsDev** [comment]
The fix is now available across all add-on stores
